Window {
	BackgroundColor: #00000044;
	TitleBackgroundColor: #00000044;

}

/* Matches all Labels who are direct children of the table */
/* This is NOT equivalent to "Window Label" */
Label {
	FontSize: 12;
	FontName: data/MaszynaAEG.ttf;
}

Button {
	BackgroundColor: #cccccc89;
	FontName: data/MaszynaAEG.ttf;
}

Button:PRELIGHT {
	BackgroundColor: #444444ff;
}

Button {
	Color: #ffffffff;
}

/* Matches all Buttons who are descendants of ScrolledWindow */
ScrolledWindow Button {
	BackgroundColor: #65432133;
}

ScrolledWindow Button:PRELIGHT {
	BackgroundColor: #00000000;
}

ScrolledWindow Button {
	Color: #ffffffff;
}

Button#close {
	BackgroundColor: #ff0000ff;
}

/* Grouping multiple selectors is also possible.
   This is the same as writing the same declarations
   in multiple rule blocks for each widget, just
   compact. :) */
CheckButton, ToggleButton {
	FontSize: 18;
}
